# Generated by Django 4.1.4 on 2022-12-26 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Author', models.CharField(max_length=30)),
                ('Edition', models.CharField(max_length=30)),
                ('Price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('Faculty', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
            ],
            options={
                'verbose_name': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateBuy', models.DateField(default=datetime.datetime(2022, 12, 26, 20, 25, 51, 53959))),
                ('Quantity', models.PositiveIntegerField()),
                ('Books_Bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.book')),
                ('Student_Bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
            options={
                'verbose_name': 'Buy',
                'verbose_name_plural': 'Buy',
            },
        ),
    ]
