# Generated by Django 4.1.4 on 2022-12-26 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='buy',
            name='DateBuy',
        ),
        migrations.AddField(
            model_name='buy',
            name='Date_Buy',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 20, 45, 39, 690896)),
        ),
    ]
